#!/usr/bin/env python3

import argparse
import sys
from src.fastq_writter import FastqWriter


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Demultiplex input fastq file based on the indexes in the samplesheet.'
    )
    requiredNamed = parser.add_argument_group('required arguments')
    requiredNamed.add_argument(
        '-i', '--input', help='Input fastq file', required=True, metavar='FASTQ_FILE'
    )
    requiredNamed.add_argument(
        '-s', '--samplesheet', help='Samplesheet in csv format', required=True, metavar='SAMPLESHEET'
    )

    parser.add_argument(
        '-o', '--output-path', help='Path to generate demultiplex files at.', required=False, metavar='PATH'
    )

    args = parser.parse_args()

    if not args.input:
        print("No input fastq file provided.")
        parser.print_usage()
        sys.exit(1)

    if not args.samplesheet:
        print("No samplesheet provided.")
        parser.print_usage()
        sys.exit(1)

    if args.output_path:
        FastqWriter(samplesheet_path=args.samplesheet,
                    fastq_file_path=args.input,
                    output_path=args.output_path).write_fastq()
    else:
        FastqWriter(samplesheet_path=args.samplesheet,
                    fastq_file_path=args.input).write_fastq()
